export default {

    imgback: require("../../assets/img/back1.jpg"),
    logohomes:require("../../assets/icons/INMOBICAPITAlMORADO.png"),
    icHome: require("../../assets/icons/house.png"),
    icUser: require("../../assets/icons/account.png"),
    newUser: require("../../assets/icons/newu.png"),
    tabmoney:require("../../assets/icons/money.png"),
    emaillogo:require("../../assets/icons/email.png"),
    password:require("../../assets/icons/password.png"),
    simu:require("../../assets/icons/inversion.png"),
    plazologo:require("../../assets/icons/plazo.png"),
    icUser1: require("../../assets/icons/acceso.png"),
    icInfo: require("../../assets/icons/info.png"),
    icEyew: require("../../assets/icons/cand.svg"),    
    icEye: require("../../assets/icons/eye.png"),
    icEyeOff: require("../../assets/icons/eyeoff.png"),
    iconicap: require("../../assets/icons/icapicon.png"),
    fondob: require("../../assets/icons/INMOBICAPITALsBLANCO.png"),
    icMoney: require("../../assets/icons/monei.png"),
    icMoneyinv: require("../../assets/icons/moneyinv.png"),
    iconlogo: require("../../assets/icons/INMOBICAPITALELEMENTOVISUAL1.png"),
    homeimg: require("../../assets/icons/inmologo.png"),
    icperfil: require("../../assets/icons/myperfil.png"),
    icregistro: require("../../assets/icons/verify.png"),
    camara: require("../../assets/icons/addcamara.png"),
    addcamara: require("../../assets/icons/addphoto.png"),
    misdatos: require("../../assets/icons/misdatos.png"),
    inversion: require("../../assets/icons/inversion.png"),
    phone:require("../../assets/icons/phonec.png"),
    mail:require("../../assets/icons/mail.png"),
    contrato:require("../../assets/icons/contrato.png"),
    simulador:require("../../assets/icons/calculadora.png"),
    logout:require("../../assets/icons/cerrar-sesion.png"),
    whats:require("../../assets/icons/social.png")
    
  };
  